@startuml system-flow_matching-diagnosis-keys-trigger-exposure-notification


Collections Apps
Actor User

group Encounter detection
...
Apps <-> App : encounter detection running
Apps -> Apps : store encounters locally
App -> App : store encounters locally 
...
end
Apps -> SubmissionAPI : uploaded diagnosis keys after pos test
...


group Match diagnosis keys
  App -> DistributionAPI : poll diagnosis keys
  App <- DistributionAPI : 

  ...

App -> App: risk analysis, match with encounters found
...
end
group Circuit breaker
  App -> CircuitBreaker : confirm exposure notification
  App <- CircuitBreaker : wait (token)
  ...
  CircuitBreaker -> CircuitBreaker : collect and aggregate (period e.g. 2h)
  CircuitBreaker -> SystemData : threshold reached

  SystemData <- ControlPanel : observe thresholds
  ...
  App -> CircuitBreaker : poll confirmation, at x time (token)
    Actor Operator
  ControlPanel -> Operator :  human decision needed
  ConfigStore <- Operator :  confirm
  CircuitBreaker <- ConfigStore : confirm

  App -> CircuitBreaker : poll confirmation, at x time (token)
  App <- CircuitBreaker : confirm
end

group Trigger notification and advice
  App -> User : trigger exposure notification for user
  App -> User : isolation advice for exposed contact
  ...
end 

@enduml