@startuml system-flow_virology-testing

Actor User


User -> App : user enters symptoms in the questionnaire
App -> User : app suggests to take a test 
User -> App : ok
App -> VirologyTestingAPI: get test URL and token
App <- VirologyTestingAPI: test URL and token
App -> App: store token


App -> User: show website URL to user
Participant VirologyWebsite #LightGrey

App -> VirologyWebsite: launch browser window and pass token ID as query parameter
User -> VirologyWebsite: website interaction for ordering a test
User <- VirologyWebsite: test ordered 
VirologyWebsite -> VirologyWebsite: do testing (hours to days)
App -> VirologyTestingAPI: poll at x time intervals (token)
...
Participant TestLab #LightGrey
VirologyWebsite -> TestLab: send swab (token)
TestLab -> TestLabAPI: send result (result, token)

TestLabAPI->VirologyTestingAPI: send result (result, token)
...
App -> VirologyTestingAPI: poll at x time intervals (token)
App <- VirologyTestingAPI: test result 

App->App: take test result action
User<-App: show/update isolation advice
ref over User, App : Share diagnosis keys and venue history
...

@enduml
