import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val com_adarshr_test_logger_gradle_plugin: String =
            "com.adarshr.test-logger:com.adarshr.test-logger.gradle.plugin:_"

    public const val aws_java_sdk_athena: String = "com.amazonaws:aws-java-sdk-athena:_"

    public const val aws_java_sdk_s3: String = "com.amazonaws:aws-java-sdk-s3:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val forkhandles_bom: String = "dev.forkhandles:forkhandles-bom:_"

    public const val result4k: String = "dev.forkhandles:result4k"

    public const val strikt_jvm: String = "io.strikt:strikt-jvm:_"

    public const val commons_csv: String = "org.apache.commons:commons-csv:_"

    public const val http4k_aws: String = "org.http4k:http4k-aws"

    public const val http4k_bom: String = "org.http4k:http4k-bom:_"

    public const val http4k_core: String = "org.http4k:http4k-core"

    public const val http4k_format_jackson: String = "org.http4k:http4k-format-jackson"

    public const val http4k_testing_hamkrest: String = "org.http4k:http4k-testing-hamkrest"

    public const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:_"

    public const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:_"

    public const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:_"

    public const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api"

    public const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine"

    public const val junit_jupiter_params: String = "org.junit.jupiter:junit-jupiter-params"

    public const val junit_bom: String = "org.junit:junit-bom:_"

    public const val bom: String = "software.amazon.awssdk:bom:_"

    public const val s3: String = "software.amazon.awssdk:s3"
}
